/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DayOfWeek } from '../models/day-of-week';
export interface DateOnly {
  day?: number;
  dayNumber?: number;
  dayOfWeek?: DayOfWeek;
  dayOfYear?: number;
  month?: number;
  year?: number;
}
