/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DateOnly } from '../models/date-only';
export interface WeatherForecast {
  date?: DateOnly;
  summary?: string | null;
  temperatureC?: number;
  temperatureF?: number;
}
